### ISSUE TITLE
Crashes on Server.

### ISSUE THREAD

**Issue by Wubzzz1337** [Cycro54/Revive_Me#1]
Not working on server it seems, atleast your Library is not.

Forge: net.minecraftforge:43.2.4[15:54:22] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Invocore (invocore) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/Options for invalid dist DEDICATED_SERVER

**Comment by Cycro54** [comment]
Ah, the first of many! I fixed the issue in **Invocore 1.19.2-3.0.5** but I can't for the life of me find out what you mean by "/review <playername>"

Can you include an example image or perhaps a link?

**Comment by Wubzzz1337** [comment]
When you are downed or someone on the server is, and you want him to get revied remotly without any assistance via a command.

So maybe ur in the Console and want to review a friend on the server you write "/review playername" and they get reviewed as if a player review them.

**Comment by Cycro54** [comment]
Oooh you meant "/revive [player name]"

That wouldn't be a bad addition at all. I'll add that as soon as I finish brainstorming a way for people in singleplayer to revive themselves (without cheats)

For now Imma mark this as resolved. If you have any other issues do let me know!

**Comment by Wubzzz1337** [comment]
You should just make it compatible with Totem of Undying that is in minecraft, right now your stuck in a death loop if u have one in your hotbar.
