### ISSUE TITLE
Can't open inventory menu (E) with Authlib-Injector

### ISSUE THREAD

**Issue by HySand** [Cycro54/Revive_Me#11]
Revive Me version 3.5.0
https://github.com/yushijinhun/authlib-injector

**Comment by Cycro54** [comment]
Alrighty, I messed up on the inventory config, but now it should be good.

Thank you for telling me, and please let me know if anything else goes wrong!
https://www.curseforge.com/minecraft/mc-mods/revive-me/files/5142009
