### ISSUE TITLE
An error had just happened when dying (Error will be in description.)

### ISSUE THREAD

**Issue by jakesmiley008** [Cycro54/Revive_Me#12]
Error: java.lang.NoSuchMethodError: 'void invoker54.invocore.client.TextUtil.renderText(com.mojang.blaze3d.vertex.PoseStack, net.minecraft.network.chat.Component, boolean, float, float, float, float, int, invoker54.invocore.client.TextUtil$txtAlignment)'
This is the first time "This" error had popped up. i had no other mods and i had the requirement, But it still crashed.

**Comment by Cycro54** [comment]
Alrighty!
Can you give me the mod version for Invocore and revive-me please?
Also are you using forge or fabric?

**Comment by jakesmiley008** [comment]
> Alrighty! Can you give me the mod version for Invocore and revive-me please? Also are you using forge or fabric?

Newest version.
Fabric.

**Comment by Cycro54** [comment]
It's a Forge mod, I have yet to make a Fabric version

**Comment by Cycro54** [comment]
I'm going to assume you don't have any other issues, so I'm going to close this. 

Please let me know if you have any other problems!
