### ISSUE TITLE
Fallen players should be forced into crawl mode

### ISSUE THREAD

**Issue by Jess521521** [Cycro54/Revive_Me#15]
I think it would look better for fallen players to be forced into crawl mode rather than just crouch. Should be a config option since it would be hard to move around while crawling if moving while downed is enabled.

**Comment by Cycro54** [comment]
You know a good amount of people mentioned this, and I guess it's about time I did something about it.

I'll implement crawling AFTER I fix all the bugs, but I can't promise when that will be since I don't currently have access to my files.

Ty for giving my mod a try though!

**Comment by Cycro54** [comment]
Alrighty, you can now change the fallen pose to Crouch, Prone, and Sleep in the latest versions
