### ISSUE TITLE
You cant die, when you got revive

### ISSUE THREAD

**Issue by jumbo7012** [Cycro54/Revive_Me#17]
I have this werid issue, when i die, my friend revive me, but then the effects like resistence and resistence to fire gone bug, when the timer got 0:00 it didnt go off, the effect where still going, and even trying drinking milk the effects just disappear from the gui, but you still can die

**Comment by jumbo7012** [comment]
![image](https://github.com/user-attachments/assets/34550457-e2f8-419b-b5c0-6be7bdbcc91b)
[2024-11-13-3.log.gz](https://github.com/user-attachments/files/17757368/2024-11-13-3.log.gz)

**Comment by Cycro54** [comment]
Ugh, that bug again x.x

I'll be able to fix it when I have access to my files again but I can't promise when that will be.

It would be of great help if you were able to post a video of it happening on here, it's hard to reproduce when playing singleplayer.

As for fixes, try the /revivemefix command, all it does is rerun the code

You can also try switching in and out of creative mode

And finally if none of that works, there's another revival mod that's called PlayerRevive. They at least shouldn't be as buggy as my mod.

**Comment by jumbo7012** [comment]
Thanks, i will try to record the video, and if it helps, i think the problem has to be related with the effect of fallen penalty, i think that when the world gone lag, the effect lag as well, and the effects stays forever

**Comment by Cycro54** [comment]
The Client was sending packets to the server which caused the server to finish the revive prematurely and not fully heal the player, fixed in the latest versions. Thanks again!
