### ISSUE TITLE
[1.16.5 server] Death is triggered twice

### ISSUE THREAD

**Issue by Watherfoxx** [Cycro54/Revive_Me#21]
**How to reproduce:**
- Kill someone
- He gives up and dies
His death is triggered twice. This was not the case in the previous version of the mod.
![image](https://github.com/user-attachments/assets/ce2a82ea-e02f-4b94-bb35-f578b086c016)

**Comment by Cycro54** [comment]
The absence of an if statement makes all the difference. Thank you for telling me, I'll be able to apply a fix soon

**Comment by Cycro54** [comment]
Okay, issue resolved. When the timer runs out my mod hits you with with the same thing that put you into the dying state, and if that doesn't kill you my mod will set your health to 0
