### ISSUE TITLE
NullPointerException: "damageSource" is null

### ISSUE THREAD

**Issue by meeprdib** [Cycro54/Revive_Me#24]
This was caused by a player leaving a server in a dying state, and whenever they try to join back, Neruina kicks them because they are in a state where they would crash the server if allowed on.
[latest.log](https://github.com/user-attachments/files/18235279/latest.log)

**Comment by Cycro54** [comment]
Whats the version?

**Comment by meeprdib** [comment]
Neoforge 1.21.1

**Comment by Cycro54** [comment]
That seems to be the wrong log file, but I should be able to guess with the version, ty for telling me!

**Comment by meeprdib** [comment]
Oh shoot, let me get the right one, one moment please

**Comment by meeprdib** [comment]
[latest.log](https://github.com/user-attachments/files/18235308/latest.log)
This should be the right one

**Comment by Cycro54** [comment]
Thank you, I'll fix it right away

**Comment by Cycro54** [comment]
When a player leaves while in the dying state the damage source that placed them in the state goes missing and the default damage source wasn't assigned. 

Fixed in the latest version, thanks again!
