### ISSUE TITLE
UI is Quite Large

### ISSUE THREAD

**Issue by MattB70** [Cycro54/Revive_Me#4]
The downed UI is quite large. An option to make it about half the size would be appreciated greatly.

_Large UI interfering with other UI elements:_
![image](https://user-images.githubusercontent.com/43189368/230991011-71ff314a-1f7d-4677-8690-f9f45a2cc415.png)

**Comment by Cycro54** [comment]
That can be achieved yes! Though, what do you have in mind? An example sketch would help immensely!

**Comment by MattB70** [comment]
Hey, I'm not the best at sketches, but here's an idea of what I'm looking for.

The image below shows a similar UI, re-using motifs from the original. The timer is centered, and a mouse icon is added to make it symbolically clear what to do. The text is generally smaller aside from the "You have fallen" and timer text. Instead of an X to cross out the item sacrifice option, it simply says the reason as to why you can't use it (this one isn't totally necessary, though I did find myself not knowing why I couldn't use it sometimes). Generally, the UI is smaller allowing the downed player to see what is going on around them, something particularly nice for multiplayer.

As you can see, I like your UI. I just think it's quite big, so much so that it becomes harder to read as you need to search the screen for info due to its size.

![UI Example](https://user-images.githubusercontent.com/43189368/231619809-43437235-0789-4997-9f47-8ec365c526c2.jpg)

**Comment by Cycro54** [comment]
Ty for the example! This should make the process a whole lot easier than going in blind. I can't promise WHEN it will be done, but it shall be done!

**Comment by Cycro54** [comment]
There is now a rough compact version in 1.19.2-3.2.0
