### ISSUE TITLE
Fallen Penalty Missing Icon

### ISSUE THREAD

**Issue by MattB70** [Cycro54/Revive_Me#6]
The Fallen Penalty effect is missing it's icon texture.

Version: 1.18.2-2.2.0

Image:
![image](https://github.com/Cycro54/Revive_Me/assets/43189368/25ff81d4-35a5-456f-b287-357dbd9a0eb4)

**Comment by Cycro54** [comment]
Ty for telling me, fixed in 1.18.2-2.2.1!
You will have to update Invocore to the latest version for 1.18.2 though
