### ISSUE TITLE
Can't revive teammates at all.

### ISSUE THREAD

**Issue by KoronX058** [Cycro54/Revive_Me#7]
Can't revive teammates in 1.19.2. Crouching shows the option to kill, but can't revive (uncrouched). No text shows up to revive. Though my friend was able to once. Our revive condition is one golden apple as displayed on the top right.
![2023-11-30_23 25 40](https://github.com/Cycro54/Revive_Me/assets/141589853/c08f7c65-1e46-43f6-9ba4-f89a04183b60)

**Comment by Cycro54** [comment]
I am having a hard time recreating this issue, do you have a modlist I can grab? 
It looks like you are using a mod that creates fake players, that could be the problem.

With the Curseforge profile I can get closer to fixing the problem
![image](https://github.com/Cycro54/Revive_Me/assets/85908325/db4b22db-eb0b-4bb8-ba89-ece22be5b2bd)

**Comment by Cycro54** [comment]
Due to inactivity, I am going to assume you resolved this. Please tell me if you have any other problems

**Comment by KoronX058** [comment]
Who are you???

**Comment by Cycro54** [comment]
I'm the developer of the player revival mod for Minecraft.

You created an issue page a while ago but never responded so I assumed it was resolved.

**Comment by KoronX058** [comment]
Ohhh, my bad. I remember now. I'll have to pull up the page in a moment.
