### ISSUE TITLE
Server crashing when picking any item from chest

### ISSUE THREAD

**Issue by iucamendonca** [Cycro54/Revive_Me#8]
[crash-2023-12-30_11.20.04-server.txt](https://github.com/Cycro54/Revive_Me/files/13798291/crash-2023-12-30_11.20.04-server.txt)

**Comment by Cycro54** [comment]
Oops, didn't account for servers. It should be a quick fix.

**Comment by Cycro54** [comment]
Thank you for telling me, it has been fixed in the latest updates
